spring.application.name=tutorial
# db
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/stock?createDatabaseIfNotExist=true
spring.datasource.username=springtuto
spring.datasource.password=jaimeleveau
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# jpa/hib

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDB53Dialect
spring.batch.jdbc.initialize-schema=always